id: IEE93E207
legacy_id: P006842
ocr_import_info:
  bdrc_scan_id: W10329
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T19:21:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:00:12.042422+00:00'
last_modified: 2022-08-29 21:00:55.934323
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10329
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW10329
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མུས་ཆེན་སངས་རྒྱས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: འཇམ་མགོན་ཨ་མེས་ཞབས།
statistics:
  ocr_word_mean_confidence_index: 0.7250874066853676
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG3597:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3597
      total_pages: 578
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3597.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7250874066853676
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
